name: O caÃ§ador de estrelas

on:
  push:
    branches:
      - main

jobs:
  reach_for_stars:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸŒŸ Checkout
        uses: actions/checkout@v2
      
      - name: ğŸš€ Iniciar a procura
        run: echo "A Procura de estrelas novas... ğŸ›°ï¸"
      
      - name: âœ¨ Descobrindo estrelas
        run: echo "Escaneando a galaxia por estrelas... ğŸŒŒ"
      
      - name: ğŸŒ  Capturando estrelas
        run: echo "Iniciando mecanismo de procura de estrelas... ğŸ“¸"
      
      - name: ğŸŒŒ Falar sobre as estrelas
        run: echo "Dizer um pouco sobre as estrelas descobertas... ğŸ“¡"

      - name: ğŸ‰ Celebrar
        run: echo "Obrigado vocÃª chegou as estrelas! ğŸ‰ğŸŒŸğŸš€"
